apiVersion: apiextensions.k8s.io/v1beta1 
kind: CustomResourceDefinition
metadata:
  name: tenantsubnets.secpaas.naps.rht 
spec:
  group: secpaas.naps.rht
  version: v1alpha
  scope: Namespaced 
  names:
    plural: tenantsubnets
    singular: tenantsubnet 
    kind: TenantSubnet
    shortNames:
    - tsub

apiVersion: secpaas.naps.rht/v1alpha
kind: TenantSubnet
metadata:
  name: tenant-one
spec:
  subnet: "10.250.0.1/24"
