#!/usr/bin/python
import kubernetes
import json
import datetime
import os
import sys

if 'KUBERNETES_PORT' in os.environ:
    print("Found KUBERNETES_PORT - Loading cluster config")
    kubernetes.config.load_incluster_config()
else:
    print("Did not find KUBERNETES_PORT -Loading kube config")
    kubernetes.config.load_kube_config()
    k8s_config = kubernetes.client.Configuration()
    k8s_config.assert_hostname = False


if 'KUBERNETES_PORT' in os.environ:
    cert_api = kubernetes.client.apis.certificates_v1beta1_api.CertificatesV1beta1Api()
else:
    cert_api = kubernetes.client.apis.CertificatesV1beta1Api()

print("CSR watch starting")
stream = kubernetes.watch.Watch().stream(cert_api.list_certificate_signing_request)
for csr in stream:
  #print(json.dumps(csr))
  csrmeta = csr['object'].metadata.to_dict()
  update_time=datetime.datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ')
  print("{}: Found at {}".format(csrmeta['name'], update_time))

  #    creationTimestamp: "2020-08-13T20:26:07Z"
 
  approval = kubernetes.client.models.v1beta1_certificate_signing_request_condition.V1beta1CertificateSigningRequestCondition(
             type='Approved',
             reason='AutoApprover',
             last_update_time=datetime.datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ')
           )
  csr['object'].status.conditions = [approval]

  print("{}: Approving".format(csrmeta['name']))
  rc = cert_api.replace_certificate_signing_request_approval(csrmeta['name'],csr['object'])

  # print('\nResult={}'.format(json.dumps(rc)))


