#!/usr/bin/python

import os,sys
import yaml
import base64
import OpenSSL

for fn in ["node3_csr1.yaml", "node3_csr_second.yaml"]:
   with open(fn,"r") as yamlin:
      mydata = yaml.load(yamlin)
      if 'items' in mydata:
         print("Username: {}".format(mydata['items'][0]['spec']['username']))
         csr_encoded=base64.b64decode(mydata['items'][0]['spec']['request'])
      else:
         print("Username: {}".format(mydata['spec']['username']))
         csr_encoded=base64.b64decode(mydata['spec']['request'])
      # print(csr_encoded)
   
      csr_decoded = OpenSSL.crypto.load_certificate_request(OpenSSL.crypto.FILETYPE_PEM, csr_encoded)
   
      csr_components = dict(csr_decoded.get_subject().get_components())
   
      print(yaml.dump(csr_components)) 
      print("")
